# Generated by Django 5.0.1 on 2024-01-28 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content_api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogs',
            name='date',
        ),
        migrations.RemoveField(
            model_name='user',
            name='date',
        ),
    ]
