# Generated by Django 5.0.1 on 2024-02-01 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_api', '0002_remove_blogs_date_remove_user_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
